### PR TITLE
Feature/graph fixes

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Go back to one-minute slider increments and make some fixes for graphs.

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
yay_graphs

**Comment by maurizi** [comment]
Bar charts! woohoo!

The other chart types aren't working for me (lots of JS errors in the console).  Maybe we should just hide the visualization selector for now?

**Comment by flibbertigibbet** [comment]
Those are next on my list. Whatever I don't get working I'll disable.

**Comment by maurizi** [comment]
:+1:

**Pull request merged**
